#!/bin/sh

# For more info, check this tutorial: https://www.atlassian.com/git/tutorials/git-hooks

# Check if this is the initial commit
if git rev-parse --verify HEAD >/dev/null 2>&1
then
    echo "pre-commit: About to create a new commit..."
    against=HEAD
else
    echo "pre-commit: About to create the first commit..."
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# Use git diff-index to check for whitespace errors
echo "pre-commit: Testing for norminette"
if ! norminette src/ incl/ > /dev/null
then
    echo "pre-commit: Aborting commit due to norm errors."
    exit 1
else
    echo "pre-commit: Norminette is OK."
    exit 0
fi
